apiVersion: v1

kind: Secret
metadata:
  name: influxdb-secrets
  namespace: monitoring
type: Opaque
stringData:
  INFLUXDB_CONFIG_PATH: /etc/influxdb/influxdb.conf
  INFLUXDB_ADMIN_USER: ulak
  INFLUXDB_ADMIN_PASSWORD: ulak123*
  INFLUXDB_DB: ulak
  INFLUXDB_USER: ulak
  INFLUXDB_USER_PASSWORD: ulak123*
