apiVersion: v1

kind: Secret
metadata:
  name: telegraf-secrets
  namespace: monitoring
type: Opaque
stringData:
  INFLUXDB_DB: telegraf
  INFLUXDB_URL: http://influxdb-service:8086
  INFLUXDB_USER: ulak
  INFLUXDB_USER_PASSWORD: ulak123
