apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
  namespace: es-cluster
  labels:
    type: local
spec:
  storageClassName: "elasticsearch-sc"
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/elasticsearch-data"
