apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: es-cluster
  labels:
    type: local
spec:
  storageClassName: "elasticsearch-sc"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
